read_2:
  adapter  : mysql
  host     : yinhe-fanti.cqziizk5ubis.ap-northeast-1.rds.amazonaws.com
  username : fantiyinhe
  password : DQbn1uumCglBSDeIMa3ZUlh0AQbZnvie
  dbname   : wk_game
  charset  : utf8
  port     : 3306

setting:
  timezone : Asia/Taipei
  callbacl_pay : http://taiwan8.client.gamehetu.com/order/complete/hetu
  secret_key : 5EUHM4s8rTLUn2MR

zone_list:
    adapter : mysql
    host    : 192.168.1.114
    user    : root
    pass    : root
    port    : 3306
    db      : center_sys
    charset : utf8
    port    : 3306

1:
  adapter : mysql
  host    : 192.168.1.114
  user    : root
  pass    : root
  port    : 3306
  db      : game_pocket
  charset : utf8
  port    : 3306