100003_1:
  host : ft-zuie.cqziizk5ubis.ap-northeast-1.rds.amazonaws.com
  username : zuie_web_r
  password : americawww&iolhjljiAnIUqy
  port : 3306
  database : game_ftht_s1

setting:
  timezone : Asia/Taipei
  callback_pay : http://52.193.120.127:7000/pay/hetu/1
  secret_key : INJOYs%ZW4r5)%(nMHDs$SriGSrnm@!3

1 :
  adapter : mysql
  host    : 192.168.1.114
  user    : root
  pass    : root
  port    : 3306
  db      : game_evile
  charset : utf8
  port    : 3306