read_2:
  adapter  : mysql
  host     : qmwjft1.cqziizk5ubis.ap-northeast-1.rds.amazonaws.com
  username : qm_ft_r
  password : qm_ft_chaAbeenfasde0+&iAnIUqy
  dbname   : cht_user_xianqian
  charset  : utf8
  port     : 3306

setting:
  timezone : Asia/Taipei
  callbacl_pay : http://taiwan8.client.gamehetu.com/order/complete/hetu
  secret_key : 5EUHM4s8rTLUn2MR

zone_list:
    adapter : mysql
    host    : 192.168.1.110
    user    : root
    pass    : root
    port    : 3306
    db      : center_sys
    charset : utf8
    port    : 3306

1:
  adapter : mysql
  host    : 192.168.1.110
  user    : root
  pass    : root
  port    : 3306
  db      : game_bio
  charset : utf8
  port    : 3306